# Generated by Django 5.2.15 on 2026-06-13 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=120, verbose_name='chamada')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('image', models.CharField(blank=True, help_text='ex.: images/sport-corrida.jpg', max_length=200, verbose_name='imagem (caminho em static/)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'modalidade',
                'verbose_name_plural': 'modalidades',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('avatar_url', models.URLField(blank=True, verbose_name='foto (URL)')),
                ('level', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20, verbose_name='nível')),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='entrou em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connections', models.ManyToManyField(blank=True, to='core.member', verbose_name='pessoas que já conheceu')),
                ('favorite_sports', models.ManyToManyField(blank=True, related_name='fans', to='core.sport', verbose_name='esportes de preferência')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('date', models.DateField(verbose_name='data')),
                ('time_label', models.CharField(blank=True, max_length=40, verbose_name='horário')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='local')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.sport', verbose_name='modalidade')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('neighborhood', models.CharField(blank=True, max_length=80, verbose_name='bairro')),
                ('schedule', models.CharField(blank=True, max_length=80, verbose_name='agenda')),
                ('is_free', models.BooleanField(default=True, verbose_name='gratuito')),
                ('members', models.ManyToManyField(blank=True, related_name='sport_groups', to='core.member', verbose_name='membros')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.sport', verbose_name='modalidade')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='nota')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='core.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.member', verbose_name='usuário')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.sport', verbose_name='modalidade')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='core.sportgroup')),
            ],
            options={
                'verbose_name': 'participação',
                'verbose_name_plural': 'participações',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.sportgroup'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='depoimento')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.member', verbose_name='usuário')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sport')),
            ],
            options={
                'verbose_name': 'depoimento',
                'verbose_name_plural': 'depoimentos',
            },
        ),
    ]
