# Generated by Django 5.2.15 on 2026-06-19 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events_joined', to='core.member', verbose_name='inscritos'),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='foto (PNG)'),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='senha (hash)'),
        ),
    ]
